$(info START ROOT MAKEFILE)
ROOT_DIR := .
BUILD_DIR := $(ROOT_DIR)/build
RVM_DIR := $(ROOT_DIR)/rvm


MAIN_ARGS := ROOT_DIR=ROOT_DIR BUILD_DIR=BUILD_DIR 

rvm: 
	make -C $(ROOT_DIR) -f $(RVM_DIR)/Makefile $(MAIN_ARGS) CUR_DIR=$(RVM_DIR)

test:
	ls


.PHONY: rvm
$(info FINISH ROOT MAKEFILE)
