
DEBUG := 1
SANITIZER := 0
CC := clang

# --------------


DEBUG_FLAGS :=
LDFLAGS := 
ifeq ($(SANITIZER),1)
DEBUG_FLAGS += -fsanitize=address
ifeq ($(CC),clang)
LDFLAGS += -fsanitize=address -static-libsan
else
LDFLAGS += -fsanitize=address -static-libasan
endif
endif

ifeq ($(DEBUG),1)
DEBUG_FLAGS += -Wall -g
endif

